import Page from '@/components/Page'
import styles from '@/styles/home-page.module.scss'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

const HomePage: NextPage = () => {
  return (
    <Page title="Home">
      <div className="flex h-screen overflow-y-auto bg-slate-900">
        <section className="m-auto flex flex-col items-center gap-4">
          <div className="relative -mb-8 h-40 w-40 shrink-0">
            <Image src="/assets/waving-devtrons-icon.gif" layout="fill" />
          </div>
          <div className="">
            <h1 data-text="Devstrons'" className={styles['water-effect']} />
          </div>
          <div className="">
            <p className="mb-8 divide-x-2 text-2xl leading-none text-slate-300 sm:text-3xl">
              <span className="inline-block px-4 uppercase transition-all hover:text-[1.1em] hover:text-sky-500">
                Learn
              </span>
              <span className="inline-block px-4 uppercase transition-all hover:text-[1.1em] hover:text-sky-500">
                Code
              </span>
              <span className="inline-block px-4 uppercase transition-all hover:text-[1.1em] hover:text-sky-500">
                Tron
              </span>
            </p>
          </div>
          <div className="flex gap-4">
            <a
              className="block rounded-md border-2 border-transparent bg-sky-500 px-4 py-2 text-center text-slate-800 transition-colors hover:border-current hover:bg-slate-900 hover:text-slate-50"
              href="https://dsc.gg/devstrons"
              rel="noopener noreferrer"
              target="_blank">
              Join Discord <i className="fa-solid fa-user-group ml-1" />
            </a>
            <a
              className="block rounded-md border-2 border-transparent bg-sky-500 px-4 py-2 text-center text-slate-800 transition-colors hover:border-current hover:bg-slate-900 hover:text-slate-50"
              href="https://devstrons.bio.link"
              rel="noopener noreferrer"
              target="_blank">
              Follow Us <i className="fa-solid fa-shuttle-space ml-1" />
            </a>
          </div>
        </section>
      </div>
    </Page>
  )
}

const _HomePage: NextPage = () => {
  return (
    <>
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
        crossOrigin="anonymous"
        referrerPolicy="no-referrer"
      />

      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="content">
          <h2>DEVSTRONS'</h2>
          <h2>DEVSTRONS'</h2>
        </div>

        <div className="flex-config">
          <div className="buttons">
            <a href="https://dsc.gg/devstrons" rel="noopener noreferrer" target="_blank">
              <div className="btn">
                Join Discord &nbsp;
                <i className="fa-solid fa-user-group"></i>
              </div>
            </a>
            <a href="https://devstrons.bio.link" rel="noopener noreferrer" target="_blank">
              <div className="btn">
                Follow Us &nbsp;
                <i className="fa-solid fa-shuttle-space"></i>
              </div>
            </a>
          </div>
        </div>
      </div>
    </>
  )
}

export default HomePage

// learn codetron
